# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\admin\Desktop\Python Programs\QT5\Hospital Management\hospital.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from PyQt5.QtWidgets import *
from PyQt5.QtGui import *
from PyQt5 import QtWidgets
from PyQt5.QtCore import *
from PyQt5 import QtCore
from PyQt5.QtWidgets import QMainWindow
from PyQt5.QtWidgets import QApplication
import pandas as pd
import sqlite3
import xlsxwriter
import sys

from os import path

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1266, 854)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(680, 770, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.refreshbtn = QtWidgets.QPushButton(Form)
        self.refreshbtn.setGeometry(QtCore.QRect(920, 770, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.refreshbtn.setFont(font)
        self.refreshbtn.setObjectName("refreshbtn")
        self.tabWidget_2 = QtWidgets.QTabWidget(Form)
        self.tabWidget_2.setGeometry(QtCore.QRect(90, 90, 1121, 671))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(15)
        self.tabWidget_2.setFont(font)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.table = QtWidgets.QTableWidget(self.tab_4)
        self.table.setGeometry(QtCore.QRect(0, 0, 1111, 621))
        self.table.setMinimumSize(QtCore.QSize(1111, 0))
        self.table.setMaximumSize(QtCore.QSize(1111, 621))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.table.setFont(font)
        self.table.setLineWidth(1)
        self.table.setMidLineWidth(0)
        self.table.setObjectName("table")
        self.table.setColumnCount(11)
        self.table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(10, item)
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.label_7 = QtWidgets.QLabel(self.tab_5)
        self.label_7.setGeometry(QtCore.QRect(10, 30, 181, 41))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.tab_5)
        self.label_8.setGeometry(QtCore.QRect(10, 110, 121, 31))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.tab_5)
        self.label_9.setGeometry(QtCore.QRect(20, 180, 101, 31))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.tab_5)
        self.label_10.setGeometry(QtCore.QRect(20, 250, 101, 31))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.tab_5)
        self.label_11.setGeometry(QtCore.QRect(500, 40, 121, 31))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.tab_5)
        self.label_12.setGeometry(QtCore.QRect(20, 330, 141, 31))
        self.label_12.setObjectName("label_12")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_7.setGeometry(QtCore.QRect(210, 40, 171, 31))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_8.setGeometry(QtCore.QRect(210, 110, 171, 31))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_9.setGeometry(QtCore.QRect(210, 180, 171, 31))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_10.setGeometry(QtCore.QRect(210, 250, 171, 31))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_11.setGeometry(QtCore.QRect(210, 330, 171, 31))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_12.setGeometry(QtCore.QRect(710, 40, 171, 31))
        self.lineEdit_12.setText("")
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.label_19 = QtWidgets.QLabel(self.tab_5)
        self.label_19.setGeometry(QtCore.QRect(500, 110, 121, 31))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.tab_5)
        self.label_20.setGeometry(QtCore.QRect(500, 180, 121, 31))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.tab_5)
        self.label_21.setGeometry(QtCore.QRect(500, 250, 121, 31))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.tab_5)
        self.label_22.setGeometry(QtCore.QRect(500, 320, 121, 31))
        self.label_22.setObjectName("label_22")
        self.lineEdit_19 = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_19.setGeometry(QtCore.QRect(710, 110, 171, 31))
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.lineEdit_20 = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_20.setGeometry(QtCore.QRect(710, 180, 171, 31))
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.lineEdit_22 = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_22.setGeometry(QtCore.QRect(710, 320, 171, 31))
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.dateEdit = QtWidgets.QDateEdit(self.tab_5)
        self.dateEdit.setGeometry(QtCore.QRect(710, 250, 171, 31))
        self.dateEdit.setObjectName("dateEdit")
        self.tabWidget_2.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.tabWidget_2.addTab(self.tab_6, "")

        self.retranslateUi(Form)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

        #ADDING THE HADNLE_BUTTON EVENT FUNCTION
        self.Handle_Buttons()
        #self.refreshbtn.clicked.connect(self.GET_DATA)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "Extract Data"))
        self.refreshbtn.setText(_translate("Form", "Refresh"))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("Form", "ID"))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("Form", "First Name"))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Last Name"))
        item = self.table.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Gender"))
        item = self.table.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Age"))
        item = self.table.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Blood Group"))
        item = self.table.horizontalHeaderItem(6)
        item.setText(_translate("Form", "Contact No"))
        item = self.table.horizontalHeaderItem(7)
        item.setText(_translate("Form", "Mail"))
        item = self.table.horizontalHeaderItem(8)
        item.setText(_translate("Form", "Date"))
        item = self.table.horizontalHeaderItem(9)
        item.setText(_translate("Form", "Disease/Symptoms"))
        item = self.table.horizontalHeaderItem(10)
        item.setText(_translate("Form", "Doctor"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("Form", "Patient Details"))
        self.label_7.setText(_translate("Form", "First Name"))
        self.label_8.setText(_translate("Form", "Last Name"))
        self.label_9.setText(_translate("Form", "Gender"))
        self.label_10.setText(_translate("Form", "Age"))
        self.label_11.setText(_translate("Form", "Contact No"))
        self.label_12.setText(_translate("Form", "Blood Group"))
        self.label_19.setText(_translate("Form", "Mail"))
        self.label_20.setText(_translate("Form", "Contact No"))
        self.label_21.setText(_translate("Form", "Date"))
        self.label_22.setText(_translate("Form", "Doctor"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("Form", "Add Info"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("Form", "Search"))


    def Handle_Buttons(self):
        self.refreshbtn.clicked.connect(self.GET_DATA)

    def GET_DATA(self):
        db=sqlite3.connect("patient_record.db")
        #db=sqlite3.connect("parts.db")
        cursor=db.cursor()

        command = ''' SELECT * from details '''
        #command=''' SELECT * from parts_table '''
        #print("Before command execution")
        result=cursor.execute(command)
        #print(str(enumerate(result)))
        self.table.setRowCount(0)

        #print("After command execution")
        for row_number, row_data in enumerate(result):
            self.table.insertRow(row_number)
            #print("In loop 1")
            for column_number, data in enumerate(row_data):
                #print("In loop 2")
                #print(str(data))
                self.table.setItem(row_number, column_number, QTableWidgetItem(str(data)))
                #print("In loop 2")
        #print("After command execution")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
